sudo: required
services:
  - docker

before_install:
  - docker build -t lucas4xin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lucas4xin/react-test npm test

after_sucess:
  - docker build -t lucas4xin/multi-client ./client
  - docker build -t lucas4xin/multi-nginx ./nginx
  - docker build -t lucas4xin/multi-server ./server
  - docker build -t lucas4xin/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lucas4xin/multi-client
  - docker push lucas4xin/multi-nginx
  - docker push lucas4xin/multi-server
  - docker push lucas4xin/multi-worker
